export const TOGGLE_TO_DO = 'TOGGLE_TO_DO'
export const DELETE_TO_DO = 'DELETE_TO_DO'
export const ADD_TO_DO = 'ADD_TO_DO'
export const UPDATE_TO_DO = 'UPDATE_TO_DO'
export const SET_CURRENT_TO_DO = 'SET_CURRENT_TO_DO'